---
title: "Pictograms for PK parameters"
author: "Jitao David Zhang"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    df_print: paged
    theme: spacelab
    mathjax: default
    code_folding: hide
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
editor_options: 
  chunk_output_type: inline
params:
  echo: yes
  relative: FALSE
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.height=3, fig.width=3)
library(ribiosUtils)
library(ribiosIO)
library(ribiosPlot)
library(openxlsx)
library(tidyverse)
library(ggplot2)
library(grid)
library(cowplot)
theme_set(theme_bw(base_size=14))
theme_update(panel.grid=element_blank(),
             legend.text = element_text(size=13),
             legend.margin = margin(),
             legend.text.align = 0, 
             legend.spacing = unit(0, "inch"),
             legend.title = element_blank(),
             panel.border = element_blank(),
             axis.text = element_blank(),
             axis.line = element_line(linewidth=0.5,
                                      arrow=grid::arrow(length=unit(0.1, "inches"),
                                                        type="closed")))
```

# Background

# Executive summary

# Analysis

## Data read in

```{r pkPlotData}
ts <- seq(0, 10, 0.1)
c0 <- 0.5
ys <- exp(-ts) * c0
ka <- 0.5
k0 <- 1
npoint <- 10
is.thalf <- which.min(abs(ys-c0/2))
thalf <- ts[is.thalf]
chalf <- ys[is.thalf]
## see https://accio.github.io/AMIDD/assets/2023/11/AMIDD-2023-11-PKPD-modelling.pdf
po <- ka * (exp(-ka * ts) - exp(-k0 * ts))/(k0 - ka)
tmax <- 1/(ka - k0) * log(ka/k0)
cmax <- po[which.min(abs(tmax - ts))]
halfdata <- data.frame(x1=c(thalf, 0),
                       x2=c(thalf, thalf),
                       y1=c(0, chalf),
                       y2=c(chalf, chalf))
cp <- data.frame(Time=c(ts, ts),
                 Value=c(ys, po), 
                 Type=rep(c("IV", "PO"), each=length(ts)))
ivCol <- "#8c510a"
poCol <- "#01665e"
poCurve <- data.frame(Time=c(0, ts, max(ts)+0.01, 0), PO=c(0, po, 0, 0), Type="AUC[PO]")
ivCurve <- data.frame(Time=c(0, ts, 0), IV=c(0, ys, 0), Type="AUC[IV]")
poMaxData <- data.frame(x1=c(tmax, 0),
                        x2=c(tmax, tmax),
                        y1=c(0, cmax),
                        y2=c(cmax, cmax))
parse.labels <- function(x) parse(text = x)
tInd <- c(c(seq(0, 10, 2),
          seq(20, 100, 15))+1,
          which.min(abs(tmax - ts)))
tPoints <- ts[tInd]
ivPoints <- ys[tInd] * rnorm(length(tInd), mean=1, sd=0.05)
poPoints <- po[tInd] * rnorm(length(tInd), mean=1, sd=0.02)
pointData <- data.frame(Time=c(tPoints, tPoints),
                 Value=c(ivPoints, poPoints), 
                 Type=rep(c("IV", "PO"), each=length(tPoints)))
```

```{r ivPlot}
ivPlot <- ggplot(cp %>% filter(Type=="IV"), 
       aes(x=Time, y=Value)) +
  geom_line(aes(x=Time, y=Value, col=Type), linewidth=1.15) +
  geom_line(aes(x=Time, y=Value, col=Type), linewidth=1.15) +
  geom_polygon(data=ivCurve, aes(x=Time, y=IV, fill=Type), alpha=0.2) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), limits=c(0, 0.55)) +
  xlab("Time") +
  ylab("Plasma concentration") +
  geom_segment(data=halfdata,
               aes(x = x1, y = y1, xend = x2, yend = y2),
               linetype=2) +
  annotate("text", x=thalf, y=chalf, label="(list(t[1/2],frac(1, 2) * C[0]))", parse=TRUE,
           hjust=0, vjust=0, size=5) +
  scale_color_manual(values = c("IV" = ivCol)) +
  scale_fill_manual(values=c("AUC[IV]"=ivCol), labels=parse.labels) +
  geom_point(data=data.frame(x=tPoints, y=ivPoints), 
             aes(x=x, y=y), size=2) +
  theme(legend.position=c(0.8, 0.9),
        legend.spacing.y = unit(0, "inch")) +
  guides(colour="none")
print(ivPlot)
```

```{r poPlot}
poPlot <- ggplot(cp %>% filter(Type=="PO"), aes(x=Time, y=Value)) +
  geom_line(aes(x=Time, y=Value, col=Type), linewidth=1.15) +
  geom_polygon(data=poCurve, aes(x=Time, y=PO, fill=Type),alpha=0.2) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(limits=c(0, max(ys)), expand=c(0,0)) +
  xlab("Time") +
  ylab("Plasma concentration") +
  geom_segment(data=poMaxData,
               aes(x = x1, y = y1, xend = x2, yend = y2),
               linetype=2) +
  annotate("text", x=tmax, y=cmax, label="(list(t[max], C[max]))", parse=TRUE,
           hjust=0, vjust=0, size=5) +
  scale_color_manual(values = c("IV" = ivCol, "PO" = poCol)) +
  scale_fill_manual(values=c("AUC[IV]"=ivCol,
                             "AUC[PO]"=poCol), labels=parse.labels) +
  geom_point(data=data.frame(x=tPoints, y=poPoints), 
             aes(x=x, y=y), inherit.aes = FALSE, size=2) +
  theme(legend.position=c(0.8, 0.9),
        legend.spacing.y = unit(0, "inch")) +
  guides(colour="none")
plot(poPlot)
```

```{r pkPlot, fig.height=3, fig.width=3}
fPlot <- ggplot(cp, aes(x=Time, y=Value)) +
  geom_line(aes(x=Time, y=Value, col=Type), linewidth=1.15) +
  geom_polygon(data=ivCurve, aes(x=Time, y=IV, fill=Type),alpha=0.2) +
  geom_polygon(data=poCurve, aes(x=Time, y=PO, fill=Type),alpha=0.2) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand=c(0, 0)) +
  xlab("Time") +
  ylab("Plasma concentration") +
  annotate("text", x=max(ts), y=max(ys)*0.77, 
           label=expression(paste("F% = ", frac(AUC[PO], AUC[IV]))), 
           hjust=1, vjust=1, size=5) +
   geom_point(data=data.frame(x=tPoints, y=ivPoints), 
             aes(x=x, y=y), size=2) +
    geom_point(data=data.frame(x=tPoints, y=poPoints), 
             aes(x=x, y=y), inherit.aes = FALSE, size=2) +
  scale_color_manual(values = c("IV" = ivCol, "PO" = poCol)) +
  scale_fill_manual(values=c("AUC[IV]"=ivCol,
                             "AUC[PO]"=poCol), labels=parse.labels) +
  theme(legend.position=c(0.8, 0.9),
        legend.spacing.y = unit(0, "inch")) + 
  guides(colour="none")
print(fPlot)
```

```{r clp}
## modified chat GPT code below
# Function to generate random points within a circle
generate_random_points <- function(n, 
                                   x_center=0,
                                   y_center=0,
                                   angle_start=0,
                                   angle_end = 2*pi,
                                   scale=0.95) {
  radii <- sqrt(runif(n))  # sqrt for uniform distribution within the circle
  angles <- runif(n, angle_start, angle_end) + 0.5 * pi
  data.frame(
    x = x_center + radii * cos(angles) * scale,
    y = y_center + radii * sin(angles) * scale
  )
}

generate_circles <- function(n=100, x_center=0, y_center=0) {
  circle_points <- data.frame(
    x = x_center + cos(seq(0, 2 * pi, length.out = n)),
    y = y_center + sin(seq(0, 2 * pi, length.out = n))
  )
  return(circle_points)
}

set.seed(1887)

points_before <- generate_random_points(200)
points_after <- generate_random_points(150, x_center=2.5, angle_end=1.5*pi)
circle_points_vss <- generate_circles(x_center=1.25, y_center=2.2)
circle_points_before <- generate_circles()
circle_points_after <- generate_circles(x_center=2.5)

# Plot the circle and the points
clpVssPlot <- ggplot(data = circle_points_before, 
               aes(x = x, y = y)) +
  geom_polygon(data = circle_points_before, 
               aes(x = x, y = y), fill = NA, 
               color = "black", linewidth=1.25) +
  geom_polygon(data = circle_points_after, 
               aes(x = x, y = y), fill = NA, 
               color = "black", linewidth=1.25) +
  geom_polygon(data = circle_points_vss, 
               aes(x = x, y = y), fill = NA, 
               color = "black", linewidth=1.25) +
  geom_point(data = points_before, aes(x = x, y = y), color = "darkgray") +
    geom_point(data = points_after, aes(x = x, y = y), color = "darkgray") +
  annotate("text", x=1.25, y=2.2, label="V[ss]", parse=TRUE,
           vjust=0.5, hjust=0.5, size=6, col="#004495") +
  annotate("text", x=0, y=-1.5, label="italic(t)", parse=TRUE,
           vjust=0, hjust=1, size=6) +
  annotate("text", x=2.5, y=-1.5, label=expression(italic(t) + Delta * italic(t)),
           vjust=0, hjust=0.5, size=6) +
  annotate("text", x=2.6, y=0.6, label="CL[p]", parse=TRUE,
           vjust=1, hjust=0, size=6, col="#004495") +
  annotate("text", x=2.75, y=2.1, label="CL[p]", parse=TRUE,
           vjust=1, hjust=0.5, size=6, col="#004495") +
  annotate("segment", x = 2.25, y = 2.2, xend = 3.25, yend = 2.2, 
         linewidth=1, linejoin = "mitre",
         arrow = arrow(type = "closed", length = unit(0.05, "npc"))) +
  coord_fixed(ratio = 1) +
  scale_x_continuous(limits=c(-1.2, 3.6), expand=c(0, 0)) +
  scale_y_continuous(limits=c(-1.8, 3.5), expand=c(0, 0)) +
  theme_void()
print(clpVssPlot)
```

```{r onePlot, fig.path="figs/", dev=c("png", "pdf"), fig.width=12, fig.height=3}
plot_grid(clpVssPlot, ivPlot, poPlot, fPlot, 
          align="v", nrow=1, labels=c("B", "C", "D", "E"))
```

```{r onePlotAlt, eval=FALSE}
ggdraw() +
  draw_plot(clpVssPlot, x=0, y=0, width=1/4, height=1) +
  draw_plot(ivPlot, x=1/4, y=0, width=1/4, height=1) +
  draw_plot(poPlot, x=2/4, y=0, width=1/4, height=1) +
  draw_plot(fPlot, x=3/4, y=0, width=1/4, height=1)
```

```{r}
write_tsv(cp, "data/PK-parameters.tsv")
write_tsv(pointData, "data/PK-parameters-points.tsv")
```

# Acknowledgment

# Session information

```{r bedaInfo}
bedaInfo()
```

```{r sessionInfo}
sessionInfo()
```

# Appendix
